### ISSUE TITLE
由于手工部署宝塔面板不支持nodejs编译，还是docker好用，改写了一个docker-compose.yml分享一下

### ISSUE THREAD

**Issue by dazhizun** [RockChinQ/free-one-api#54]
docker-compose.yml
```yaml
version: '3'
services:
  free-one-api:
    container_name: free-one-api
    image: rockchin/free-one-api
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ~/free-one-api/data:/app/data
```
